config/routes.rb
Cms::Application.routes.draw do

  
  namespace :admin do
    root :to => "home#index"
    match "login" => "user_sessions#new"
    match "logout" => "user_sessions#destroy"
    resources :pages
    resources :assets
    resources :users
    resources :user_sessions
  end

  match '/editor(/*requested_uri)(.:format)' => 'mercury#edit'
  
  
  
  
  

  root :to => 'pages#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name,  :presence => true
  validates :email, :presence => true, :uniqueness => true, :email_format => true
  belongs_to :group

  acts_as_authentic do |c|
    c.login_field = :email            # email is the login field
    c.validate_login_field = false    # There is no login field, so don't validate it
  end

  def admin?
    return self.group.id == 1
  end

end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::AdminController
  load_and_authorize_resource

  # GET /users
  # GET /users.xml
  def index
    @users = User.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @users }
      format.rss
    end
  end

  # GET /users/1
  # GET /users/1.xml
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/new
  # GET /users/new.xml
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.xml
  def create
    @user = User.new(params[:user])

    respond_to do |format|
      if @user.save
        format.html { redirect_to(:admin_users, :notice => 'User was successfully created.') }
        format.xml  { render :xml => @user, :status => :created, :location => @user }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.xml
  def update
    @user = User.find(params[:id])
    puts "="*100
#    params[:user][:group] = Group.find(params[:user][:group]) unless @user.nil?
    puts params

    respond_to do |format|
      if @user.update_attributes(params[:user])
        format.html { redirect_to(:admin_users, :notice => 'User was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @user.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.xml
  def destroy
    @user = User.find(params[:id])
    @user.destroy

    respond_to do |format|
      format.html { redirect_to(admin_users_url) }
      format.xml  { head :ok }
    end
  end

end

app/views/admin/users/_usernav.html.erb
<%= link_to "Neuer User", new_admin_user_path %>

app/views/admin/users/edit.html.erb
<%= form_for @user, :as => :user, :url => { :action => "update" } do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :group %><br />
    <%= f.collection_select(:group_id, Group.all, :id, :name, :prompt => true) %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>

app/views/admin/users/index.html.erb
<div class="admin-nav">
  <ul>
    <li>
      <%= link_to "Nutzer" %>
    </li>
    <li>
      <%= link_to "Gruppen"%>
    </li>
  </ul>
</div>
<div class="admin-content">
  <div id="users">
    <%= render :partial => "admin/users/usernav" %>
    <h2>Nutzerliste</h2>
    <table class="admin-table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Gruppe</th>
          <th>eMail</th>
          <th>&nbsp;</th>
        </tr>
      </thead>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= user.group.name %></td>
          <td><%= user.email %></td>
          <td><%= link_to "Edit", edit_admin_user_path(user.id) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/admin/users/new.html.erb
<h2>Neuer Nutzer</h2>
<%= form_for @user, :as => :user, :url => { :action => "create" } do |f| %>
  <p>
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </p>
  <p>
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.label :group %><br />
    <%= f.collection_select(:group_id, Group.all, :id, :name, :prompt => true) %>
  </p>
  <p><%= f.submit "Submit" %></p>
<% end %>